<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

		<!-- CSS -->
		<?php
		    echo $this->headLink(array(
		        'rel' => 'shortcut icon',
		        'type' => 'image/vnd.microsoft.icon',
		        'href' => $this->basePath() . '/img/favicon.ico'
		    ))
			->appendStylesheet($this->basePath() . '/dist/css/skins/_all-skins.min.css')
			->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
			->appendStylesheet($this->basePath() . '/dist/css/AdminLTE.min.css')
			->appendStylesheet($this->basePath() . '/plugins/iCheck/square/blue.css')
			->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
		?>
	</head>
	<body class="hold-transition login-page">
		<div class="login-box">
			<div class="login-logo">
				<a href="<?php echo $this->url('home'); ?>"><b>Admin Panel</b></a>
			</div>

			<div class="login-box-body">
				<?php echo $this->content; ?>
			</div>

		</div>
		<?php
		echo $this->headScript()
			->appendFile($this->basePath() . '/js/jquery.min.js')
			->appendFile($this->basePath() . '/js/bootstrap.min.js')
		    ->appendFile($this->basePath() . '/plugins/iCheck/icheck.min.js')
		    ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
		    ->appendFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9'));
		?>

	    <script>
	      $(function () {
	        $('input').iCheck({
	          checkboxClass: 'icheckbox_square-blue',
	          radioClass: 'iradio_square-blue',
	          increaseArea: '20%' // optional
	        });
	      });
	    </script>

	</body>
</html>
