<?php
/**
 * @todo Initialise the view
 */
$title = 'View User';
$this->headTitle($title);
?>
<div class="user-view">
	<div class="row">
		<div class="col-md-12">
			<h3><?php echo $title; ?></h3>
			<table id="w0" class="table table-striped table-bordered detail-view">
			    <tbody>
			        <tr>
						<th>User ID</th>
						<td><?php echo $model->pkUserID; ?></td>
					</tr>

					<tr>
						<th>Full Name</th>
						<td><?php echo $model->userFullName; ?></td>
					</tr>

					<tr>
						<th>Email</th>
						<td><?php echo $model->userEmail; ?></td>
					</tr>

					<tr>
						<th>Gender</th>
						<td><?php echo ($model->userGender) ? 'Male' : 'Female'; ?></td>
					</tr>

					<tr>
						<th>User Added</th>
						<td><?php echo $model->userAdded; ?></td>
					</tr>

					<tr>
						<th>User Status</th>
						<td>
						<?php
							if($model->userStatus == 0)
							{
								echo 'Inactive';
							}
							elseif($model->userStatus == 1)
							{
								echo 'Active';
							}
							elseif($model->userStatus == 2)
							{
								echo 'Blocked';
							}
							elseif($model->userStatus == 3)
							{
								echo 'Deleted';
							}
							else
							{
								echo 'Something is wrong';
							}
						?></td>
					</tr>

			    </tbody>
			</table>
		</div>
	</div>
</div>
